// UserInfo constants
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST';
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS';
export const ADD_ITEMS_FAIL = 'ADD_ITEMS_FAIL';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAIL = 'GET_ITEM_FAIL';

export const DELETE_ITEM_SUCCESS='DELETE_ITEM_SUCCESS'

export const GET_ITEM_BY_ID_SUCCESS='GET_ITEM_BY_ID_SUCCESS'
export const GET_ITEM_BY_ID_REQUEST='GET_ITEM_BY_ID_REQUEST'

export const UPDATE_ITEM='UPDATE_ITEM'